{   'inputs': [   {   'note': 'tag with two of the same single char words',
                      'orm_object': 'Tag',
                      'tag': 'a aa',
                      'str_attrs': {'tag': 'a aa'}}],
    'debug': False,
    'echo': False,
    'db_result': [   ('select COUNT(*) from alias;', 0),
                     ('select COUNT(*) from aliasword;', 0),
                     ('select COUNT(*) from bookmark;', 0),
                     ('select COUNT(*) from filename;', 0),
                     ('select COUNT(*) from tag;', 1),
                     ('select COUNT(*) from tag_relationship;', 0),
                     ('select COUNT(*) from tagbookmarks;', 0),
                     ('select COUNT(*) from tagword;', 2),
                     ('select COUNT(*) from word;', 2),
                     ('select COUNT(*) from wordmisspelling;', 0)]}
